services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: audiobook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data18
    command: -c 'max_connections=400'

volumes:
  db_volume:
