import {
  pgTable,
  uuid,
  text,
  integer,
  varchar,
  timestamp,
  pgEnum,
  index,
  real,
} from "drizzle-orm/pg-core";
import { audiobooks } from "./audiobook.js";
import { sql } from "drizzle-orm";

export const assetTypeEnum = pgEnum("asset_type", [
  "raw_upload", // The original PDF/TXT uploaded by the user
  "parsed_text", // The raw strings outputted by the parser
  "chunk_text", // The segmented blocks outputted by the chunker,
  "tagged_text", // The enriched text outputted by the LLM tagger
  "cover_image", // The audiobook cover
  "hls_manifest", // m3u8 playlists
  "tts_output", // audio segments generated by TTS before stitching
  "final_audio", // the final stitched audiobook audio file (e.g. mp3 or wav)
]);

export const assets = pgTable(
  "assets",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    audiobookId: uuid("audiobook_id").references(() => audiobooks.id, {
      onDelete: "cascade",
    }),

    type: assetTypeEnum("type").notNull(),

    // Storage exact location
    bucketName: varchar("bucket_name", { length: 255 }).notNull(),
    s3Key: text("s3_key").notNull(),

    // File Meta
    fileName: varchar("file_name", { length: 500 }),
    mimeType: varchar("mime_type", { length: 100 }),
    sizeBytes: integer("size_bytes"),

    // Multipart upload
    uploadId: text("upload_id"),
    uploadExpiresAt: timestamp("upload_expires_at"),

    // for hls
    sequenceNumber: integer("sequence_number"),
    durationSeconds: real("duration_seconds"),

    createdAt: timestamp("created_at")
      .defaultNow()
      .notNull()
      .$onUpdate(() => sql`CURRENT_TIMESTAMP`),
  },
  (table) => [
    index("assets_audiobook_idx").on(table.audiobookId),
    index("assets_type_idx").on(table.type),
    index("assets_audiobook_type_idx").on(table.audiobookId, table.type), // maybe don't need?
  ],
).enableRLS();
